Adjust HaXml build system for polyparse instead.

diff --git a/src/Makefile b/src/Makefile
--- a/src/Makefile
+++ b/src/Makefile
@@ -1,49 +1,17 @@
-SOFTWARE = HaXml
-VERSION = 1.17
+SOFTWARE = polyparse
+VERSION = 1.00
 
 LIBSRCS = \
-	Text/XML/HaXml.hs Text/XML/HaXml/Combinators.hs Text/XML/HaXml/Lex.hs \
-	Text/XML/HaXml/Posn.hs \
-	Text/XML/HaXml/Parse.hs Text/XML/HaXml/Pretty.hs \
-	Text/XML/HaXml/Types.hs Text/XML/HaXml/Validate.hs \
-	Text/XML/HaXml/Wrappers.hs \
-	Text/XML/HaXml/OneOfN.hs \
-	Text/XML/HaXml/ParseLazy.hs \
-	Text/XML/HaXml/ByteStringPP.hs \
-	Text/XML/HaXml/TypeMapping.hs  Text/XML/HaXml/XmlContent.hs \
-	Text/XML/HaXml/Verbatim.hs Text/XML/HaXml/Escape.hs \
-	Text/XML/HaXml/SAX.hs \
-	Text/XML/HaXml/ShowXmlLazy.hs \
-	Text/XML/HaXml/Html/Generate.hs Text/XML/HaXml/Html/Parse.hs \
-	Text/XML/HaXml/Html/Pretty.hs \
-	Text/XML/HaXml/Html/ParseLazy.hs \
-	Text/XML/HaXml/Xtract/Combinators.hs \
-	Text/XML/HaXml/Xtract/Lex.hs \
-	Text/XML/HaXml/Xtract/Parse.hs \
 	Text/ParserCombinators/HuttonMeijer.hs \
 	Text/ParserCombinators/HuttonMeijerWallace.hs \
 	Text/ParserCombinators/Poly.hs \
 	Text/ParserCombinators/PolyState.hs \
 	Text/ParserCombinators/PolyLazy.hs \
 	Text/ParserCombinators/PolyStateLazy.hs \
-	Text/ParserCombinators/TextParser.hs \
+	Text/Parse.hs \
 
 LIBOBJS = $(patsubst %.hs, %.o, $(LIBSRCS))
 
-TOOLSRCS = \
-	Text/XML/HaXml/DtdToHaskell/TypeDef.hs \
-	Text/XML/HaXml/DtdToHaskell/Convert.hs \
-	Text/XML/HaXml/DtdToHaskell/Instance.hs \
-	tools/DtdToHaskell.hs tools/Xtract.hs tools/Validate.hs \
- 	tools/Canonicalise.hs tools/MkOneOf.hs \
- 	tools/CanonicaliseLazy.hs tools/XtractLazy.hs
-
-TOOLSET = \
-	../../DtdToHaskell$(EXE) ../../Xtract$(EXE) ../../Validate$(EXE) \
-	../../Canonicalise$(EXE) ../../MkOneOf$(EXE) \
-	../../CanonicaliseLazy$(EXE) ../../XtractLazy$(EXE)
-
-EXE = $(shell cat ../exe)
 OUT = $(shell cat ../out)
 INSTALLDIR = $(shell cat ../prefix)
 WHOLEARCHIVE = $(shell cat ../ldopt)
@@ -52,7 +20,7 @@ WHOLEARCHIVE = $(shell cat ../ldopt)
 COMPILER := $(findstring ghc, $(HC))
 ifeq "$(COMPILER)" "ghc"
 COMPILE  = $(HC) --make -cpp -i. $(shell cat ghcpkgs) \
-		-package-name HaXml-$(VERSION) -DVERSION=$(VERSION)
+		-package-name $(SOFTWARE)-$(VERSION) -DVERSION=$(VERSION)
 RENAME   = mv $(OUT)
 endif
 COMPILER := $(findstring nhc98, $(HC))
@@ -62,32 +30,31 @@ COMPILE  = hmake -hc=$(HC) -I. -K4M +CTS -H8M -CTS -package base \
 RENAME   = echo Built
 endif
 
-.PHONY: all libs toolset
+.PHONY: all libs
 
-all: libs toolset
-libs: libHSHaXml.a
-toolset: $(TOOLSET)
+all: libs
+libs: libHS$(SOFTWARE).a
 install-filesonly-ghc: libs $(INSTALLDIR)
-	cp libHSHaXml.a `cat ghclibdir`
-	-ranlib `cat ghclibdir`/libHSHaXml.a	# ignore if fails on Linux
-	-cp HSHaXml.o `cat ghclibdir`		# file may not exist on MacOS X
-	rm -rf `cat ghcincdir`/HaXml
-	mkdir -p `cat ghcincdir`/HaXml
-	cp interfaces.tar `cat ghcincdir`/HaXml
-	cd `cat ghcincdir`/HaXml; tar xf interfaces.tar; rm interfaces.tar
+	cp libHS$(SOFTWARE).a `cat ghclibdir`
+	-ranlib `cat ghclibdir`/libHS$(SOFTWARE).a	# ignore if fails on Linux
+	-cp HS$(SOFTWARE).o `cat ghclibdir`		# file may not exist on MacOS X
+	rm -rf `cat ghcincdir`/$(SOFTWARE)
+	mkdir -p `cat ghcincdir`/$(SOFTWARE)
+	cp interfaces.tar `cat ghcincdir`/$(SOFTWARE)
+	cd `cat ghcincdir`/$(SOFTWARE); tar xf interfaces.tar; rm interfaces.tar
 	cp $(TOOLSET) $(INSTALLDIR)
 install-filesonly-nhc98: libs $(INSTALLDIR)
-	cp libHSHaXml.a `cat nhc98libdir`/`harch`
-	-ranlib `cat nhc98libdir`/`harch`/libHSHaXml.a
-	rm -rf `cat nhc98incdir`/HaXml
-	mkdir -p `cat nhc98incdir`/HaXml
-	cp interfaces.tar `cat nhc98incdir`/packages/HaXml
-	cd `cat nhc98incdir`/packages/HaXml; tar xf interfaces.tar; rm interfaces.tar
+	cp libHS$(SOFTWARE).a `cat nhc98libdir`/`harch`
+	-ranlib `cat nhc98libdir`/`harch`/libHS$(SOFTWARE).a
+	rm -rf `cat nhc98incdir`/$(SOFTWARE)
+	mkdir -p `cat nhc98incdir`/$(SOFTWARE)
+	cp interfaces.tar `cat nhc98incdir`/packages/$(SOFTWARE)
+	cd `cat nhc98incdir`/packages/$(SOFTWARE); tar xf interfaces.tar; rm interfaces.tar
 	cp $(TOOLSET) $(INSTALLDIR)
-install-ghc: install-filesonly-ghc HaXml.pkgconf
-	`cat ghcpkgcmd` --remove-package=HaXml || true	# ignore any error
+install-ghc: install-filesonly-ghc $(SOFTWARE).pkgconf
+	`cat ghcpkgcmd` --remove-package=$(SOFTWARE) || true	# ignore any error
 	`cat ghcpkgcmd` --add-package <pkg.conf || \
-	`cat ghcpkgcmd` register HaXml.pkgconf
+	`cat ghcpkgcmd` register $(SOFTWARE).pkgconf
 	echo "you can safely ignore any errors from --add-package"
 install-nhc98: install-filesonly-nhc98
 install-tools-hugs: toolset-hugs $(INSTALLDIR)
@@ -96,9 +63,9 @@ install-tools-hugs: toolset-hugs $(INSTALLDIR)
 # update the sources if necessary
 $(LIBSRCS) $(TOOLSRCS) Makefile: %: ../../src/%
 	cp $< $@
-HaXml.pkgconf: ../../HaXml.cabal ghcincdirraw ghclibdirraw
-	cp ../../HaXml.cabal $@
-	echo "import-dirs:	`cat ghcincdirraw`HaXml" >>$@
+$(SOFTWARE).pkgconf: ../../$(SOFTWARE).cabal ghcincdirraw ghclibdirraw
+	cp ../../$(SOFTWARE).cabal $@
+	echo "import-dirs:	`cat ghcincdirraw`$(SOFTWARE)" >>$@
 	echo "library-dirs:	`cat ghclibdirraw`" >>$@
 	echo "depends:		base, haskell98" >>$@
 	echo "hs-libraries:	HS$(SOFTWARE)" >>$@
@@ -106,26 +73,11 @@ HaXml.pkgconf: ../../HaXml.cabal ghcincdirraw ghclibdirraw
 
 
 # packaged library
-libHSHaXml.a: $(LIBSRCS)
+libHS$(SOFTWARE).a: $(LIBSRCS)
 	$(COMPILE) $(LIBSRCS)
-	ar r libHSHaXml.a $(LIBOBJS)
-	-ld -r $(WHOLEARCHIVE) -o HSHaXml.o libHSHaXml.a	# for GHCi only
+	ar r libHS$(SOFTWARE).a $(LIBOBJS)
+	-ld -r $(WHOLEARCHIVE) -o $(SOFTWARE).o libHS$(SOFTWARE).a	# for GHCi only
 	tar cf interfaces.tar `find Text -name *.hi -print`
-
-
-# standalone tools
-$(TOOLSET): $(LIBSRCS) $(TOOLSRCS)
-	cd tools; $(COMPILE) -i.. $(patsubst ../../%${EXE}, %, $@)
-	cd tools; $(RENAME) $(patsubst ../../%, %, $@)
-	mv $(patsubst ../../%, tools/%, $@) ../..
-
-toolset-hugs:
-	for file in tools/*.hs ;\
-	do tool=`basename $$file .hs` ;\
-	   echo '#!'`which runhugs` >$$tool ;\
-	   cat $$file >>$$tool ;\
-	   chmod +x $$tool ;\
-	done
 
 $(INSTALLDIR):
 	if [ ! -d $(INSTALLDIR) ] ; then mkdir -p $(INSTALLDIR); fi
